### PR TITLE
Updated for better use with the new API endpoints

### PR DESCRIPTION
**Pull request by KyleBoyer**
In this push request, I have updated the following:

In \__init\__.py I added new functions that include:
- clear_convo
- auth_token_login
- get_snaptag
- get_chat_media
- send_typing_notification
Also, I changed how some existing functions work, and updating them to use the new API methods.

In utils.py I changed the user-agent to look more authentic with the requests being made, to Snapchat's servers. Also I changed the URL variable to allow use of different endpoints(the ones the new API implemented).

__Note__: The Travis-CI build will fail due to a connection error, however the script itself works perfectly.

### CODE REVIEW

**Comment by KyleBoyer** [comment]
Any reason why this is not merged?

**Comment by martinp** [comment]
Are all these changes required to implement the missing methods? Also, I don't see why it's necessary to change the API endpoints in the existing methods, unless they have stopped working?

As I mentioned in your previous PR, I'd rather see a single PR for each new method introduced. For example, `clear_convo` goes into one PR.

The tests fail because you didn't mock the new URLs that have been introduced.

**Comment by KyleBoyer** [comment]
I see what you're saying about the PR's. Also the existing functions are not working now... Snapchat has started to lock accounts when using this script as is right now. In fact soon we will have to update to use the 9.X user agent. Finally, can you explain how I can mock the new URLs?

**Comment by martinp** [comment]
Sure, I'm using https://github.com/dropbox/responses to mock HTTP requests. 

[This](https://github.com/martinp/pysnap/blob/master/tests/pysnap_tests.py#L66) for example, says that for any request to URL `https://feelinsonice-hrd.appspot.com/bq/logout`, respond with an empty body and status code 200.

So when `self.snapchat.logout()` is called in that test, it will hit the mocked response, and not the actual API endpoint.

**Pull request closed without merging**
