### PR TITLE
Update URLs and UserAgent so library now working again.

### PR DESCRIPTION
**Pull request by charlesbalderson**
- I've updated the URLs due to an API change.
- PyCrypto has been swapped out for Cryptography, it's better maintained and generally seems to be easier to install.
- setup.cfg has been created to facilitate publishing to PyPi, have tested publishing to https://testpypi.python.org/pypi and worked perfectly.

### CODE REVIEW

**Comment by martinp** [comment]
Thanks for your contribution. Can you also update the tests so that they pass with these changes?

**Comment by willcray** [comment]
When I went to pull the updates, it told me my local repo was already up to
date. Also, I'm trying to run a script to enable group snapchat stories,
and I'm getting this exception:

[image: Inline image 1]

Any ideas?

Thank You,

Will


Will Cray
Electrical & Computer Engineer
University of Virginia 2017

**Comment by martinp** [comment]
@willcray Please hold off until it's merged.

**Comment by charlierm** [comment]
@martinp @willcray Apologies, I've had a busy couple of days, I will get those tests fixed this evening. I plan on writing some integration tests when I get a chance.

**Comment by charlierm** [comment]
I think this still need a bit of work, the API seems to have changed a fair bit over the last few months.

**Comment by charlierm** [comment]
@martinp ready to be merged :chicken:

**Comment by martinp** [comment]
@charlierm Nice,, thanks!

**Comment by willcray** [comment]
[image: Inline image 1]

Still getting this error


Will Cray
Electrical & Computer Engineer
University of Virginia 2017

**Comment by JosephRedfern** [comment]
@willcray your screenshot hasn't attached - can you post via GitHub rather than replying to email?

**Comment by KrissiBT** [comment]
im just getting an error while trying to import cryptography==1.2.2
im using pip

**Comment by jkeat** [comment]
screen shot 2016-02-08 at 3 49 49 pm

**Comment by KrissiBT** [comment]
im still getting an error

**Comment by JosephRedfern** [comment]
@KrissiBT: I suspect that you need to run `sudo apt-get install build-essential python-dev` before doing the . The `cryptography` module uses native code that pip is attempting to compile.

**Comment by KrissiBT** [comment]
@JosephRedfern  you are where right i fixed that 
but im still facing an error 
and i think i have installed all the packages that are required

**Comment by rjvir** [comment]
Has anyone tested this and gotten it working recently? Seems like it's still not compatible with any current Snapchat API.

**Comment by willcray** [comment]
I would really appreciate it if someone could get this working. Still says my version of snapchat is outdated when I run my script.

**Comment by KrissiBT** [comment]
why am i getting this error
https://camo.githubusercontent.com/bf0d29ed367ae20bb466adc35b0890b5b64d7887/687474703a2f2f7075752e73682f6e304f6e422f373861393566373864632e706e67

**Comment by JohnMaguire** [comment]
@martinp Do you plan to submit pysnap to PyPI? Seems this pull request did most of the work for you. :) I'd love to be able simply add pysnap to my `requirements.txt`

**Comment by martinp** [comment]
@JohnMaguire Not at the moment. Note that pip supports installing directly from git, you can add something like this to your `requirements.txt`:

```
-e git+https://github.com/martinp/pysnap.git@master#egg=pysnap
```

**Comment by JohnMaguire** [comment]
Wow! I never knew that. Thanks a ton @martinp

**Comment by willcray** [comment]
Have there been any updates to get this working yet?


Will Cray
Electrical & Computer Engineer
University of Virginia 2017

**Comment by 700ghz** [comment]
I get `requests.exceptions.SSLError: hostname 'app.snapchat.com' doesn't match either of '*.appspot.com', '*.thinkwithgoogle.com', '*.withgoogle.com', '*.withyoutube.com', 'appspot.com', 'thinkwithgoogle.com', 'withgoogle.com', 'withyoutube.com'`
Then I have added `verify=False` to request functions and it works. 

But now I am getting: `You're using a version of Snapchat or operating system that's no longer supported. Please upgrade your device's operating system and update to the newest app version to use Snapchat. Thanks!`

How I can fix it?
Thanks!

**Comment by Snowlav** [comment]
Seems like SC dropped support for the version you are using in your UA.
Try updating UA version, it's worth a shot but you'll probably face a more
recent error.

**Comment by 700ghz** [comment]
@Snowlav ok, I have changed UA to `'User-Agent': 'Snapchat/9.39.5.0 (Nexus 4; Android 17; gzip)'` and not I am getting: `Oh no! Your login temporarily failed, so please try again later. If your login continues to fail, please visit https://support.snapchat.com/a/failed-login :)`. 
My login and password are correctly (100%).
Any ideas? :)

**Comment by Snowlav** [comment]
Yes authentication differs from version, so you'd need an up to date way to
authorize.

Just for the record, what version were you using before? (In your UA)

**Comment by 700ghz** [comment]
UA before: `'User-Agent': 'Snapchat/9.2.0.0 (A0001; Android 4.4.4#5229c4ef56#19; gzip)'`

**Comment by Snowlav** [comment]
Can you try the version right after 9.2.0.0 on Android? (for example
9.2.0.1)

Check apkmirror or something to see what version came after 9.2.0.0

**Comment by 700ghz** [comment]
@Snowlav ok, all versions older than Snapchat/9.17.0.0 are returning: `You're using a version of Snapchat or operating system that's no longer supported...` But Snapchat/9.17.0.0 and higher are returning : `Your login temporarily failed, so please try again later...`

Any ideas? :)

**Comment by 700ghz** [comment]
My current UA: `'User-Agent': 'Snapchat/9.17.0.0 (A0001; Android 4.4.4#5229c4ef56#19; gzip)'`

**Comment by Snowlav** [comment]
I guess you are out of luck as far as this API goes, I'm sorry :(

To use the later versions of snapchat we need a new method of
authentication.
If you have some reverse engineering skills you might be able to achieve
something using a MITM proxy and magisk on Android.

Haven't looked into it myself yet, but Magisk seems to be able to bypass
safetynet so you'll atleast be able to grab an auth token.

**Comment by Snowlav** [comment]
as far as iOS goes it's a completely different story but from what I've
heard it should be similar to instagram (as in using a client side HMAC of
the payload) so you could try to dig into the iOS app if you have xcode or
something similar.

**Comment by 700ghz** [comment]
@Snowlav Oh, I have understood. It's not easy. I'll think about it. Thanks :)

**Comment by Snowlav** [comment]
No worries, perhaps me or other people will find time to work on it in the
near future :)

**Pull request merged**
