### PR TITLE
added media type to send_to_story method

### PR DESCRIPTION
**Pull request by gurinderhans**

### CODE REVIEW

**Comment by agermanidis** [comment]
This would break existing code. It's better to have it as an optional arg:

https://github.com/agermanidis/pysnap/commit/3d9389858fa197bb0faf01eab4d32139b84946e5

**Comment by martinp** [comment]
Thanks @gurinderhans, but as @agermanidis mentions, not breaking the API is better.

**Comment by gurinderhans** [comment]
May I ask how? You can use some sort of custom method to find the media type. The current method only works for snap images, what if you wanted to send a video to the story?

**Comment by agermanidis** [comment]
In the sense that existing code using the method would have to be changed so it can support it. Basically I suggested the exact same change as you did, only with media_type as a keyword argument instead of a positional one.

I think the best solution is probably wrapping the image or video as a media object and then passing that instead of passing the media id directly, but for now this works well enough.

**Comment by gurinderhans** [comment]
makes sense :)

**Pull request closed without merging**
